export const robotsConfig = {
  policy: [
    { userAgent: 'AI2Bot', disallow: '/' },
    { userAgent: 'Ai2Bot-Dolma', disallow: '/' },
    { userAgent: 'Amazonbot', disallow: '/' },
    { userAgent: 'anthropic-ai', disallow: '/' },
    { userAgent: 'Applebot', disallow: '/' },
    { userAgent: 'Applebot-Extended', disallow: '/' },
    { userAgent: 'Brightbot 1.0', disallow: '/' },
    { userAgent: 'Bytespider', disallow: '/' },
    { userAgent: 'CCBot', disallow: '/' },
    { userAgent: 'ChatGPT-User', disallow: '/' },
    { userAgent: 'Claude-Web', disallow: '/' },
    { userAgent: 'ClaudeBot', disallow: '/' },
    { userAgent: 'cohere-ai', disallow: '/' },
    { userAgent: 'cohere-training-data-crawler', disallow: '/' },
    { userAgent: 'Crawlspace', disallow: '/' },
    { userAgent: 'Diffbot', disallow: '/' },
    { userAgent: 'DuckAssistBot', disallow: '/' },
    { userAgent: 'FacebookBot', disallow: '/' },
    { userAgent: 'FriendlyCrawler', disallow: '/' },
    { userAgent: 'Google-Extended', disallow: '/' },
    { userAgent: 'GoogleOther', disallow: '/' },
    { userAgent: 'GoogleOther-Image', disallow: '/' },
    { userAgent: 'GoogleOther-Video', disallow: '/' },
    { userAgent: 'GPTBot', disallow: '/' },
    { userAgent: 'iaskspider/2.0', disallow: '/' },
    { userAgent: 'ICC-Crawler', disallow: '/' },
    { userAgent: 'ImagesiftBot', disallow: '/' },
    { userAgent: 'img2dataset', disallow: '/' },
    { userAgent: 'ISSCyberRiskCrawler', disallow: '/' },
    { userAgent: 'Kangaroo Bot', disallow: '/' },
    { userAgent: 'Meta-ExternalAgent', disallow: '/' },
    { userAgent: 'Meta-ExternalFetcher', disallow: '/' },
    { userAgent: 'OAI-SearchBot', disallow: '/' },
    { userAgent: 'omgili', disallow: '/' },
    { userAgent: 'omgilibot', disallow: '/' },
    { userAgent: 'PanguBot', disallow: '/' },
    { userAgent: 'PerplexityBot', disallow: '/' },
    { userAgent: 'PetalBot', disallow: '/' },
    { userAgent: 'Scrapy', disallow: '/' },
    { userAgent: 'SemrushBot-OCOB', disallow: '/' },
    { userAgent: 'SemrushBot-SWA', disallow: '/' },
    { userAgent: 'Sidetrade indexer bot', disallow: '/' },
    { userAgent: 'Timpibot', disallow: '/' },
    { userAgent: 'VelenPublicWebCrawler', disallow: '/' },
    { userAgent: 'Webzio-Extended', disallow: '/' },
    { userAgent: 'YouBot', disallow: '/' },
    { userAgent: '*', allow: '/' },
  ],
  sitemap: true,
};
